name: Docker Image CI Incognito

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'zulu' # Alternative distribution options are available. 

    - name: Build and analyze
      env:
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -DskipTests=true -Dsonar.projectKey=ruslan8424_incognito-api-public  
      working-directory: ./incongnito-api 

    - name: Build the Docker image
      run: docker build  -t ${{ secrets.DOCKERHUB_USERNAME }}/incognito-api-public:${{ github.sha }} .     

    - name: Test Image # check if the image was created, for test purposes
      run: docker images 

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.20.0
      with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/incognito-api-public:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

    - name: Docker Login 
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}   

    - name: Docker Push
      run: docker push  ${{ secrets.DOCKERHUB_USERNAME }}/incognito-api-public:${{ github.sha }}


    # name: Scan code with Sonar Cloud
    # uses: sonarsource/sonarcloud-github-action@v3.0.0 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
    # env:
    #  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 

    - name: Deploy to EC2 instance 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }} # used the bastion key!!DJgV- Bastion pub, GlvbgECAw- Bastion private,
        script:
          docker stop incognito-api-public || true
          docker rm incognito-api-public || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/incognito-api-public:${{ github.sha }}
          docker run -d name incognito-api-public -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/incognito-api-public:${{ github.sha }}







